### ISSUE TITLE
Some custom playlists don't work

### ISSUE THREAD

**Issue by Zenigata** [mdean808/audial#10]
I have just tried once with: https://audial.mogdan.xyz/custom?playlist=0bK9fcPuK3J8IvkDHjkeDM

I can see this error:
```
GET https://us-central1-audial-6e1bd.cloudfunctions.net/daily?playlist=0bK9fcPuK3J8IvkDHjkeDM&random=false&locale=Wed Apr 05 2023
[HTTP/3 500 Internal Server Error 2178ms]
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Comment by mdean808** [comment]
This is a playlist of podcasts -- audial does not support podcasts.

**Comment by Zenigata** [comment]
Thanks for your reactivity! Is it complicated to support a playlist of podcasts? I want to do it :)
