### ISSUE TITLE
change default playlist

### ISSUE THREAD

**Issue by faroit** [mdean808/audial#7]
👋 this is a really nice heardle clone! 

Currently it doesn't support saving custom playlist daily game status, right? I wondered if I could fork the project and modify the default playlist. But it looks like this is done in some cloud [function api](https://github.com/mdean808/audial/blob/master/src/lib/spotify.ts#L5 ) which isn't open-source, is that correct?

**Comment by mdean808** [comment]
Sure thing. The API actually is [open source](https://github.com/mdean808/audial-firebase).

To save the game status, I'd suggest just using [localstorage through nanostores](https://github.com/nanostores/persistent), as there is no leaderboard or reason to maintain concurrency of scores between players. 

The firebase functions are just so I can have a way to request data from spotify without leaking my API key.
