### ISSUE TITLE
With long playlists, some songs will never be chosen

### ISSUE THREAD

**Issue by lucymcknight** [mdean808/audial#9]
I have a playlist that is over 25 hours in length, containing 100s of songs, and it is also growing pretty rapidly as it is a collaborative playlist where one new album gets added every week. I have noticed, based on experimentation with the auto-complete, that not all of the albums are even possible options in the game. I totally understand that it might not be possible to populate the full list of songs on such a long playlist, but it is a bummer that some songs will never be chosen as the song of the day. 

I am wondering if it's possible to rotate the window of available songs every day so that each song will be equally likely to be chosen in the long term? For example, if today it shows songs 1-100 as options, then tomorrow it would pick from songs 101-200 instead, or something like that. Or maybe something like, pick one random song out of the whole list, and then for the options list, load all songs at indices +/- N from the index of the chosen song. 

Of course, if it's possible to simply load the full list, that'd be even better!

Thanks for all the work you put into this game; my friends and I have been enjoying it so far! 😊

**Comment by mdean808** [comment]
Unfortunately it is a limitation of the Spotify API that prevents all songs from appearing. Audial uses the preview track associated with most songs for its audio, and some songs don't have a public preview track associated with them so I have to filter those out. 
To have every song be playable I would have to force the user to log in to Spotify when they attempt to play -- something I'd rather not do.
